#!/bin/bash

# Quick Fix Commands for Production Deployment
# Run these commands on the server to fix the 502 error

echo "=========================================="
echo "QUICK FIX FOR 502 ERROR"
echo "=========================================="
echo ""
echo "Run these commands on your server:"
echo ""
echo "# 1. Pull latest changes from GitHub"
echo "git pull origin main"
echo ""
echo "# 2. Stop all containers"
echo "docker-compose -f docker-compose.prod.yml down"
echo ""
echo "# 3. Remove old database volume (optional)"
echo "docker volume rm mushqila_postgres_data"
echo ""
echo "# 4. Start services with new configuration"
echo "docker-compose -f docker-compose.prod.yml up -d --build"
echo ""
echo "# 5. Wait for services to start"
echo "sleep 20"
echo ""
echo "# 6. Run migrations on AWS RDS"
echo "docker-compose -f docker-compose.prod.yml exec -T web python manage.py migrate"
echo ""
echo "# 7. Collect static files"
echo "docker-compose -f docker-compose.prod.yml exec -T web python manage.py collectstatic --noinput"
echo ""
echo "# 8. Check status"
echo "docker-compose -f docker-compose.prod.yml ps"
echo ""
echo "=========================================="
