# Generated by Django 5.1.4 on 2026-03-03 22:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('aws_access_key', models.CharField(blank=True, max_length=255)),
                ('aws_secret_key', models.CharField(blank=True, max_length=255)),
                ('aws_region', models.CharField(default='us-east-1', max_length=50)),
                ('ses_verified', models.BooleanField(default=False)),
                ('s3_bucket_name', models.CharField(blank=True, max_length=255)),
                ('s3_inbox_prefix', models.CharField(default='inbox/', max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('from_address', models.EmailField(db_index=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('bcc_addresses', models.JSONField(blank=True, default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(db_index=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('s3_url', models.URLField(blank=True, max_length=1000)),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash'), ('spam', 'Spam'), ('archive', 'Archive')], db_index=True, default='inbox', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_starred', models.BooleanField(db_index=True, default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('references', models.TextField(blank=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='webmail.emailaccount')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_url', models.URLField(max_length=1000)),
                ('content_id', models.CharField(blank=True, max_length=255)),
                ('is_inline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='webmail.email')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='EmailFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition_field', models.CharField(choices=[('from', 'From'), ('to', 'To'), ('subject', 'Subject'), ('body', 'Body')], max_length=20)),
                ('condition_value', models.CharField(max_length=255)),
                ('condition_operator', models.CharField(default='contains', max_length=20)),
                ('action_type', models.CharField(choices=[('move_to_folder', 'Move to Folder'), ('add_label', 'Add Label'), ('mark_as_read', 'Mark as Read'), ('mark_as_starred', 'Mark as Starred'), ('delete', 'Delete')], max_length=20)),
                ('action_value', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='webmail.emailaccount')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='webmail.emailaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLabelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assignments', to='webmail.email')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_assignments', to='webmail.emaillabel')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='webmail.emailaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('email_count', models.IntegerField(default=0)),
                ('last_emailed', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', 'name', 'email'],
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['account', 'folder', '-received_at'], name='webmail_ema_account_d0b316_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['account', 'is_read', '-received_at'], name='webmail_ema_account_911af6_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['thread_id', '-received_at'], name='webmail_ema_thread__1763a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emaillabel',
            unique_together={('account', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='emaillabelassignment',
            unique_together={('email', 'label')},
        ),
    ]
