# Generated by Django 5.2.5 on 2026-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmail', '0002_emailaccount_alternate_email_emailaccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
