# Generated by Django 5.2.8 on 2025-12-18 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissiontransaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_commission_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_commissions', to='accounts.flightbooking'),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='hajj_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_commissions', to='accounts.hajjpackage'),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_commissions', to='accounts.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_flight_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='airline',
            field=models.ForeignKey(limit_choices_to={'supplier_type': 'airline'}, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_flights', to='accounts.servicesupplier'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_hotel_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(limit_choices_to={'supplier_type': 'hotel'}, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_hotel_bookings', to='accounts.servicesupplier'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='flight_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_invoices', to='accounts.flightbooking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hajj_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_invoices', to='accounts.hajjpackage'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_invoices', to='accounts.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='umrah_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_invoices', to='accounts.umrahpackage'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='flight_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_refunds', to='accounts.flightbooking'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_refunds', to='accounts.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='original_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_refunds', to='accounts.payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_requested_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_refunds', to=settings.AUTH_USER_MODEL),
        ),
    ]
