# Generated by Django 4.2.7 on 2026-01-26 17:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('accounts', '0003_account_accountingperiod_accountingrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Transaction Number')),
                ('transaction_type', models.CharField(choices=[('ticket_issue', 'Ticket Issue'), ('ticket_void', 'Ticket Void'), ('ticket_cancel', 'Ticket Cancel'), ('ticket_refund', 'Ticket Refund'), ('ticket_reissue', 'Ticket Reissue'), ('payment_received', 'Payment Received'), ('payment_refunded', 'Payment Refunded'), ('commission_earned', 'Commission Earned'), ('commission_paid', 'Commission Paid'), ('ancillary_purchase', 'Ancillary Purchase'), ('ancillary_refund', 'Ancillary Refund'), ('emd_issue', 'EMD Issue'), ('emd_void', 'EMD Void'), ('emd_refund', 'EMD Refund')], db_index=True, max_length=30, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Base Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Fee Amount')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Commission Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='Currency')),
                ('description', models.TextField(verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('accounting_posted', models.BooleanField(default=False, verbose_name='Posted to Accounting')),
                ('accounting_posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('journal_entry_reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Journal Entry Reference')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Is Reversed')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reversed At')),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('agent', models.ForeignKey(limit_choices_to={'user_type__in': ['agent', 'super_agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='flights.booking')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='accounts.transactionlog')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('reverse', 'Reverse'), ('post_accounting', 'Post to Accounting')], max_length=20, verbose_name='Action Type')),
                ('action_description', models.TextField(verbose_name='Action Description')),
                ('state_before', models.JSONField(blank=True, null=True, verbose_name='State Before')),
                ('state_after', models.JSONField(blank=True, null=True, verbose_name='State After')),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.transactionlog')),
            ],
            options={
                'verbose_name': 'Transaction Audit Log',
                'verbose_name_plural': 'Transaction Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAgentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Total Transactions')),
                ('tickets_issued', models.IntegerField(default=0, verbose_name='Tickets Issued')),
                ('tickets_voided', models.IntegerField(default=0, verbose_name='Tickets Voided')),
                ('tickets_cancelled', models.IntegerField(default=0, verbose_name='Tickets Cancelled')),
                ('tickets_refunded', models.IntegerField(default=0, verbose_name='Tickets Refunded')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gross Sales')),
                ('total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Refunds')),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Sales')),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Commission Earned')),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Commission Paid')),
                ('net_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Commission')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Opening Balance')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Closing Balance')),
                ('detailed_data', models.JSONField(default=dict, verbose_name='Detailed Data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type__in': ['agent', 'super_agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Agent Report',
                'verbose_name_plural': 'Monthly Agent Reports',
                'ordering': ['-year', '-month', 'agent'],
            },
        ),
        migrations.CreateModel(
            name='DailyTransactionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_date', models.DateField(db_index=True, verbose_name='Summary Date')),
                ('tickets_issued', models.IntegerField(default=0, verbose_name='Tickets Issued')),
                ('tickets_voided', models.IntegerField(default=0, verbose_name='Tickets Voided')),
                ('tickets_cancelled', models.IntegerField(default=0, verbose_name='Tickets Cancelled')),
                ('tickets_refunded', models.IntegerField(default=0, verbose_name='Tickets Refunded')),
                ('tickets_reissued', models.IntegerField(default=0, verbose_name='Tickets Reissued')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Sales')),
                ('total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Refunds')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Commissions')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Revenue')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Opening Balance')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Closing Balance')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type__in': ['agent', 'super_agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Transaction Summary',
                'verbose_name_plural': 'Daily Transaction Summaries',
                'ordering': ['-summary_date', 'agent'],
            },
        ),
        migrations.CreateModel(
            name='AgentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Entry Date')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10, verbose_name='Entry Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balance Before')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balance After')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type__in': ['agent', 'super_agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.transactionlog')),
            ],
            options={
                'verbose_name': 'Agent Ledger Entry',
                'verbose_name_plural': 'Agent Ledger Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['agent', 'transaction_date'], name='accounts_tr_agent_i_9fa230_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_type', 'status'], name='accounts_tr_transac_84bda7_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['booking', 'transaction_type'], name='accounts_tr_booking_a46697_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionauditlog',
            index=models.Index(fields=['transaction_log', 'performed_at'], name='accounts_tr_transac_b9b920_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionauditlog',
            index=models.Index(fields=['performed_by', 'performed_at'], name='accounts_tr_perform_91ed65_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyagentreport',
            index=models.Index(fields=['agent', 'year', 'month'], name='accounts_mo_agent_i_9e07e6_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyagentreport',
            index=models.Index(fields=['year', 'month'], name='accounts_mo_year_b56d29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyagentreport',
            unique_together={('agent', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='dailytransactionsummary',
            index=models.Index(fields=['agent', 'summary_date'], name='accounts_da_agent_i_ff797f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytransactionsummary',
            index=models.Index(fields=['summary_date'], name='accounts_da_summary_1aff5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytransactionsummary',
            unique_together={('agent', 'summary_date')},
        ),
        migrations.AddIndex(
            model_name='agentledger',
            index=models.Index(fields=['agent', 'entry_date'], name='accounts_ag_agent_i_85a6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentledger',
            index=models.Index(fields=['agent', 'entry_type'], name='accounts_ag_agent_i_c1952c_idx'),
        ),
    ]
