# Generated by Django 5.2.5 on 2026-04-29 17:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('settlement_days', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('adjustment', 'Adjustment')], default='bank_transfer', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.airline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=20)),
                ('ticket_number', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField()),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=120)),
                ('passenger_name', models.CharField(max_length=120)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('airline_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void'), ('refund', 'Refund'), ('reissue', 'Reissue')], default='issued', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounting.airline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.payment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='accounting.sale')),
            ],
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['issue_date'], name='accounting__issue_d_a122ff_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='accounting__status_f3cd26_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user', 'issue_date'], name='accounting__user_id_29f37c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'sale')},
        ),
    ]
